/* eslint-disable */
/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join, resolve } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 12, is-linux-musl is not available so check /usr/bin/ldd
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'nanograph.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nanograph.darwin-x64.node')
          } else {
            nativeBinding = require('nanograph-db-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'nanograph.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nanograph.darwin-arm64.node')
          } else {
            nativeBinding = require('nanograph-db-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          throw new Error('musl libc is not supported')
        } else {
          localFileExisted = existsSync(join(__dirname, 'nanograph.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./nanograph.linux-x64-gnu.node')
            } else {
              nativeBinding = require('nanograph-db-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          throw new Error('musl libc is not supported')
        } else {
          localFileExisted = existsSync(join(__dirname, 'nanograph.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./nanograph.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('nanograph-db-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'nanograph.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nanograph.win32-x64-msvc.node')
          } else {
            nativeBinding = require('nanograph-db-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Database } = nativeBinding
const { tableFromIPC } = require('apache-arrow')

function decodeArrow(buffer) {
  return tableFromIPC(buffer)
}

function mediaFile(file, mimeType) {
  return mimeType == null ? { file } : { file, mimeType }
}

function mediaBase64(base64, mimeType) {
  return mimeType == null ? { base64 } : { base64, mimeType }
}

function mediaUri(uri, mimeType) {
  return mimeType == null ? { uri } : { uri, mimeType }
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value) && !Buffer.isBuffer(value)
}

function isMediaRef(value) {
  if (!isPlainObject(value)) {
    return false
  }
  const keys = Object.keys(value)
  if (keys.length === 0) {
    return false
  }
  const allowed = new Set(['file', 'base64', 'uri', 'mimeType'])
  if (!keys.every((key) => allowed.has(key))) {
    return false
  }
  const sourceKeys = ['file', 'base64', 'uri'].filter((key) => value[key] != null)
  return sourceKeys.length === 1
}

function buildMediaMimeMap(schemaDescription) {
  const map = new Map()
  const absorb = (typeDefs) => {
    for (const typeDef of typeDefs || []) {
      const propMap = new Map()
      for (const prop of typeDef.properties || []) {
        if (prop.mediaMimeProp) {
          propMap.set(prop.name, prop.mediaMimeProp)
        }
      }
      map.set(typeDef.name, propMap)
    }
  }
  absorb(schemaDescription?.nodeTypes)
  absorb(schemaDescription?.edgeTypes)
  return map
}

function serializeMediaRef(value) {
  if (value.file != null) {
    return {
      encoded: `@file:${resolve(String(value.file))}`,
      mimeType: value.mimeType ?? null,
    }
  }
  if (value.base64 != null) {
    return {
      encoded: `@base64:${String(value.base64)}`,
      mimeType: value.mimeType ?? null,
    }
  }
  return {
    encoded: `@uri:${String(value.uri)}`,
    mimeType: value.mimeType ?? null,
  }
}

function serializeLoadData(typeName, data, mediaMimeMap) {
  if (!isPlainObject(data)) {
    throw new Error(`loadRows row for '${typeName}' must have an object data payload`)
  }

  const out = { ...data }
  const typeMediaMap = mediaMimeMap.get(typeName) || new Map()

  for (const [key, value] of Object.entries(data)) {
    if (!isMediaRef(value)) {
      continue
    }
    const { encoded, mimeType } = serializeMediaRef(value)
    out[key] = encoded

    const mimeProp = typeMediaMap.get(key)
    if (!mimeProp || mimeType == null) {
      continue
    }

    const existingMime = out[mimeProp]
    if (existingMime == null) {
      out[mimeProp] = mimeType
      continue
    }
    if (existingMime !== mimeType) {
      throw new Error(
        `media MIME mismatch for ${typeName}.${key}: helper mimeType '${mimeType}' conflicts with '${existingMime}' in '${mimeProp}'`,
      )
    }
  }

  return out
}

function serializeLoadRow(row, mediaMimeMap) {
  if (!isPlainObject(row)) {
    throw new Error('loadRows expects row objects')
  }

  if (typeof row.type === 'string') {
    return {
      type: row.type,
      data: serializeLoadData(row.type, row.data || {}, mediaMimeMap),
    }
  }

  if (typeof row.edge === 'string') {
    if (typeof row.from !== 'string' || typeof row.to !== 'string') {
      throw new Error(`edge row '${row.edge}' must include string 'from' and 'to' values`)
    }
    const encoded = {
      edge: row.edge,
      from: row.from,
      to: row.to,
    }
    const data = row.data || {}
    if (Object.keys(data).length > 0) {
      encoded.data = serializeLoadData(row.edge, data, mediaMimeMap)
    }
    return encoded
  }

  throw new Error("loadRows row must include either 'type' or 'edge'")
}

Database.prototype.loadRows = async function loadRows(rows, mode) {
  if (!Array.isArray(rows)) {
    throw new Error('loadRows expects an array of rows')
  }
  const schema = await this.describe()
  const mediaMimeMap = buildMediaMimeMap(schema)
  const jsonl = rows
    .map((row) => JSON.stringify(serializeLoadRow(row, mediaMimeMap)))
    .join('\n')
  return this.load(jsonl, mode)
}

module.exports.Database = Database
module.exports.decodeArrow = decodeArrow
module.exports.mediaFile = mediaFile
module.exports.mediaBase64 = mediaBase64
module.exports.mediaUri = mediaUri
